# ===== CONEXIÓN BD (VALHALA S.A.C.) =====
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/valhala_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.hikari.maximum-pool-size=50

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===== SERVIDOR =====
server.port=8080
# ===== JWT (RNF-05) =====
jwt.secret=VALHALA_SAC_SUPER_SECRETO_JWT_2026_LINEA_AMARILLA_FLOTA_GPS
jwt.expiration-ms=86400000